# Generated by Django 4.2.3 on 2023-08-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0003_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
