# Generated by Django 4.2.3 on 2023-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0006_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=' ', upload_to='advertisements/', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
